name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ github.token }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
